name: dataaugmentation
channels:
  - ostrokach
  - defaults
  - conda-forge
  - vgauthier
  - rwest
  - pytorch
  - anaconda
dependencies:
  - appnope=0.1.2
  - backcall=0.2.0
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - ipykernel=6.15.2
  - ipython=7.31.1
  - jedi=0.18.1
  - jupyter_client=7.4.8
  - libcxx=14.0.6
  - libedit=3.1.20221030
  - libffi=3.4.2
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - openssl=1.1.1s
  - packaging=22.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pygments=2.11.2
  - python=3.7.15
  - python-dateutil=2.8.2
  - pyzmq=23.2.0
  - readline=8.2
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.8
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - attrs==22.2.0
      - babel==2.11.0
      - beautifulsoup4==4.11.1
      - bleach==6.0.0
      - cffi==1.15.1
      - charset-normalizer==3.0.1
      - defusedxml==0.7.1
      - fastjsonschema==2.16.2
      - idna==3.4
      - importlib-resources==5.10.2
      - ipython-genutils==0.2.0
      - jinja2==3.1.2
      - json5==0.9.11
      - jsonschema==4.17.3
      - jupyter-core==4.12.0
      - jupyter-server==1.23.5
      - jupyterlab==3.5.3
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.19.0
      - mistune==2.0.4
      - nbclassic==0.5.1
      - nbclient==0.7.2
      - nbconvert==7.2.9
      - nbformat==5.7.3
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - pandocfilters==1.5.0
      - pkgutil-resolve-name==1.3.10
      - prometheus-client==0.16.0
      - pycparser==2.21
      - pyrsistent==0.19.3
      - requests==2.28.2
      - send2trash==1.8.0
      - sniffio==1.3.0
      - soupsieve==2.3.2.post1
      - terminado==0.17.1
      - tinycss2==1.2.1
      - tomli==2.0.1
      - urllib3==1.26.14
      - webencodings==0.5.1
      - websocket-client==1.5.0
